default_settings: null
behaviors:
  Soccer Bot:
    trainer_type: sac
    hyperparameters:
      batch_size: 512
      buffer_size: 500000
      learning_rate: 0.0001
      learning_rate_schedule: constant
      tau: 0.0025
    checkpoint_interval: 2000
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.05
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 500000
    time_horizon: 200
    summary_freq: 2000
    self_play:
      save_steps: 10000
      team_change: 15000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
checkpoint_settings:
  results_dir: mlagent_results

