default_settings: null
behaviors:
  Soccer Bot:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0001
      learning_rate_schedule: constant
      batch_size: 512
      buffer_size: 500000
      buffer_init_steps: 0
      tau: 0.0025
      steps_per_update: 1
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 1
    checkpoint_interval: 2000
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      curiosity:
        gamma: 0.99
        strength: 0.05
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.0003
        encoding_size: null
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 500000
    time_horizon: 200
    summary_freq: 2000
    threaded: false
    self_play:
      save_steps: 10000
      team_change: 15000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    behavioral_cloning: null
env_settings:
  env_path: b5-serverbuild_forcebased_manyenvs\SoccerBot
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  timeout_wait: 60
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 50.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
  no_graphics_monitor: false
environment_parameters: null
checkpoint_settings:
  run_id: sac_final_2
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: mlagent_results
torch_settings:
  device: null
debug: false
